const demoSnapshot={run:{run_id:"RUN-2026-0817-0007",status:"SUCCEEDED",incident_id:"QI-2026-0817-0042",revision:5,completed_task_count:3,task_count:3},coordinator:{status:"SUCCEEDED",revision:2,agent_role:"coordinator",execution_id:"EXE-COORD-0007"},tasks:[{task_id:"TASK-Q-0007",target_agent_role:"quality",status:"SUCCEEDED",attempt_count:1},{task_id:"TASK-P-0007",target_agent_role:"production",status:"SUCCEEDED",attempt_count:1},{task_id:"TASK-S-0007",target_agent_role:"sla",status:"SUCCEEDED",attempt_count:1}],fusion:{proposed_action:"HOLD_BATCH",has_conflict:false,fusion_round:1},risk:{decision:"REQUIRE_APPROVAL",risk_level:"HIGH",approval_required:true,proposed_action:"HOLD_BATCH"},approval:{status:"APPROVED",revision:2,approval_key:"APR-2026-0817-0007"}};
const $=id=>document.getElementById(id);const esc=value=>String(value??"Not available");
function statusClass(status){return String(status??"unknown").toLowerCase()}
function showNotice(message){$("notice").textContent=message;$("notice").hidden=false;setTimeout(()=>$("notice").hidden=true,4500)}
function validSnapshot(data){return data&&typeof data==="object"&&!Array.isArray(data)&&data.run&&typeof data.run==="object"&&Array.isArray(data.tasks)&&data.tasks.every(task=>task&&typeof task==="object")}
function render(snapshot){if(!validSnapshot(snapshot))throw new Error("Snapshot must include a run object and task array.");const run=snapshot.run,tasks=snapshot.tasks;$("runId").textContent=esc(run.run_id);$("incidentLine").textContent=`Quality incident · ${esc(run.incident_id)}`;const status=esc(run.status).toUpperCase();const runStatus=$("runStatus");runStatus.textContent=status;runStatus.className=`run-status ${statusClass(status)}`;$("runRevision").textContent=esc(run.revision);$("taskProgress").textContent=`${run.completed_task_count??tasks.filter(t=>t.status==="SUCCEEDED").length}/${run.task_count??tasks.length}`;$("taskProgressNote").textContent=`${tasks.length} specialist task${tasks.length===1?"":"s"}`;$("coordinatorStatus").textContent=esc(snapshot.coordinator?.status).toUpperCase();$("approvalStatus").textContent=esc(snapshot.approval?.status).toUpperCase();$("approvalNote").textContent=snapshot.approval?.revision?`Revision ${snapshot.approval.revision}`:"Approval gate";$("taskCount").textContent=`${tasks.length} task${tasks.length===1?"":"s"}`;$("taskRows").replaceChildren(...tasks.map(task=>{const row=document.createElement("tr");row.innerHTML=`<td class="task-id"></td><td class="role"></td><td><span class="status-pill"></span></td><td></td>`;row.children[0].textContent=esc(task.task_id);row.children[1].textContent=esc(task.target_agent_role);row.children[2].firstChild.textContent=esc(task.status);row.children[2].firstChild.className=`status-pill ${statusClass(task.status)}`;row.children[3].textContent=esc(task.attempt_count);return row;}));const chain=[['Coordinator',snapshot.coordinator?.status],['Fusion',snapshot.fusion?.proposed_action],['Risk',snapshot.risk?.decision],['Approval',snapshot.approval?.status]];$("decisionChain").replaceChildren(...chain.map(([label,value],index)=>{const item=document.createElement("div");item.className="chain-item";item.innerHTML=`<span class="chain-mark">${index+1}</span><div><div class="chain-label"></div><div class="chain-value"></div></div><span class="status-pill"></span>`;item.children[1].children[0].textContent=label;item.children[1].children[1].textContent=label==="Risk"?`${snapshot.risk?.risk_level??"Not available"} risk gate`:label==="Fusion"?`Round ${snapshot.fusion?.fusion_round??"-"}`:"Lifecycle state";item.children[2].textContent=esc(value);item.children[2].className=`status-pill ${statusClass(value)}`;return item;}));detail("approvalDetails",[["Approval key",snapshot.approval?.approval_key],["Status",snapshot.approval?.status],["Revision",snapshot.approval?.revision],["Action",snapshot.risk?.proposed_action]]);detail("coordinatorDetails",[["Execution",snapshot.coordinator?.execution_id],["Status",snapshot.coordinator?.status],["Revision",snapshot.coordinator?.revision],["Fusion round",snapshot.fusion?.fusion_round]]);$("updatedAt").textContent=`Loaded ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`}
function detail(id,rows){$(id).replaceChildren(...rows.map(([key,value])=>{const row=document.createElement("div");row.className="detail-row";row.innerHTML='<span class="detail-key"></span><span class="detail-value"></span>';row.children[0].textContent=key;row.children[1].textContent=esc(value);return row;}))}
function loadFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);render(data)}catch(error){showNotice(error.message||"Unable to load snapshot")}};reader.onerror=()=>showNotice("Unable to read snapshot file");reader.readAsText(file)}
$("loadButton").addEventListener("click",()=>$("snapshotInput").click());$("loadNav").addEventListener("click",()=>{$("sidebar").classList.remove("open");$("snapshotInput").click()});$("snapshotInput").addEventListener("change",event=>loadFile(event.target.files[0]));$("menuButton").addEventListener("click",()=>$("sidebar").classList.toggle("open"));
async function loadInitialSnapshot(){try{const response=await fetch("/api/snapshot",{headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`Snapshot API returned ${response.status}`);const data=await response.json();render(data);$("updatedAt").textContent="Live snapshot · API"}catch(error){try{render(demoSnapshot);$("updatedAt").textContent="Demo fallback · API unavailable";showNotice("Live Snapshot unavailable; showing the bundled demo view.")}catch(fallbackError){showNotice(fallbackError.message)}}}
loadInitialSnapshot();
