package com.factoryops.business.batch.api;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.factoryops.business.batch.application.BatchApplicationService;import com.factoryops.business.batch.domain.*;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.junit.jupiter.*;import org.testcontainers.mysql.MySQLContainer;
@SpringBootTest(properties="factoryops.clock.fixed=2026-08-13T08:00:00Z") @AutoConfigureMockMvc @Testcontainers class BatchLifecycleHttpIT {
 @Container static final MySQLContainer MYSQL=new MySQLContainer("mysql:8.4");@DynamicPropertySource static void mysql(DynamicPropertyRegistry r){r.add("spring.datasource.url",MYSQL::getJdbcUrl);r.add("spring.datasource.username",MYSQL::getUsername);r.add("spring.datasource.password",MYSQL::getPassword);}@Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;@Autowired BatchApplicationService service;
 @BeforeEach void clean(){jdbc.update("DELETE FROM vision_inspection_results");jdbc.update("DELETE FROM inspections");jdbc.update("DELETE FROM batches WHERE kind='PRODUCTION'");}
 @Test void creates_replays_conflicts_and_queries()throws Exception{var body="{\"batch_id\":\"B-17\",\"product_code\":\"P-1\",\"production_line\":\"LINE-2\"}";mvc.perform(post("/api/v1/batches").contentType("application/json").content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("OPEN"));mvc.perform(post("/api/v1/batches").contentType("application/json").content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.replayed").value(true));mvc.perform(get("/api/v1/batches/B-17")).andExpect(status().isOk());mvc.perform(post("/api/v1/batches").contentType("application/json").content(body.replace("P-1","P-2"))).andExpect(status().isConflict());}
 @Test void holds_and_replays_same_command()throws Exception{service.create("B-17","P-1","LINE-2");var body="{\"reason_code\":\"PROCESS_ANOMALY\",\"reason_detail\":\" pressure \"}";mvc.perform(post("/api/v1/batches/B-17/hold").contentType("application/json").content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.replayed").value(false));mvc.perform(post("/api/v1/batches/B-17/hold").contentType("application/json").content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.replayed").value(true));}
 @Test void legacy_is_queryable_but_not_actionable()throws Exception{mvc.perform(get("/api/v1/batches/SYS-LEGACY-UNASSIGNED")).andExpect(status().isOk()).andExpect(jsonPath("$.kind").value("LEGACY_UNASSIGNED"));mvc.perform(post("/api/v1/batches/SYS-LEGACY-UNASSIGNED/hold").contentType("application/json").content("{\"reason_code\":\"PROCESS_ANOMALY\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("batch_not_actionable"));}
 @Test void internal_release_is_terminal_and_has_no_http_route()throws Exception{service.create("B-17","P-1","LINE-2");service.hold("B-17",HoldCommand.manual(HoldReasonCode.PROCESS_ANOMALY,"x"));var command=ReleaseCommand.external(ReleaseReasonCode.RECHECK_PASSED,"ok");assertThat(service.release("B-17",command).replayed()).isFalse();assertThat(service.release("B-17",command).replayed()).isTrue();mvc.perform(post("/api/v1/batches/B-17/release").contentType("application/json").content("{}")).andExpect(status().isNotFound());}
 @Test void concurrent_different_holds_keep_one_winner(){service.create("B-17","P-1","LINE-2");var start=new CountDownLatch(1);var ex=Executors.newFixedThreadPool(2);try{var fs=List.of(ex.submit(()->outcome(start,HoldReasonCode.PROCESS_ANOMALY)),ex.submit(()->outcome(start,HoldReasonCode.MANUAL_QUALITY_HOLD)));start.countDown();assertThat(fs).extracting(f->f.get()).containsExactlyInAnyOrder("APPLIED","CONFLICT");}catch(Exception e){throw new RuntimeException(e);}finally{ex.shutdownNow();}}
 @Test void concurrent_identical_batch_creates_one_row(){var start=new CountDownLatch(1);var ex=Executors.newFixedThreadPool(2);try{var fs=List.of(ex.submit(()->{start.await();return service.create("B-17","P-1","LINE-2").replayed();}),ex.submit(()->{start.await();return service.create("B-17","P-1","LINE-2").replayed();}));start.countDown();assertThat(fs).extracting(f->f.get()).containsExactlyInAnyOrder(false,true);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM batches WHERE batch_id='B-17'",Integer.class)).isEqualTo(1);}catch(Exception e){throw new RuntimeException(e);}finally{ex.shutdownNow();}}
 private String outcome(CountDownLatch s,HoldReasonCode c)throws Exception{s.await();try{return service.hold("B-17",HoldCommand.manual(c,"x")).replayed()?"REPLAY":"APPLIED";}catch(BatchCommandConflictException e){return "CONFLICT";}}
}
