spring:
  application:
    name: factoryops-business-service
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
